### ISSUE TITLE
Setting sweep and modulation doesn't give any output at DAC

### ISSUE THREAD

**Issue by sahraghav57** [WarwickEPR/RePLIA#1]
I tried using LIAControl.jar to write the lock-in data onto a file on the host PC. 

When I apply the modulation voltage (0.5V) and constant sweep of 0V, and sweep setting (-0.95V to 0.95V over 5s), neither of DACs give an output. I have tried setting this using the .jar file as well as via command line.

**Comment by GavinMorleyLab** [comment]
Sorry but I don't know how to help. The RePLIA software is not maintained anymore, and there are other implementations of Red-Pitaya lock-in amplifiers that are better eg:
https://marceluda.github.io/rp_lock-in_pid
