### ISSUE TITLE
Unable to write data using LIAControl.jar

### ISSUE THREAD

**Issue by sahraghav57** [WarwickEPR/RePLIA#2]
I tried using LIAControl.jar to write the lock-in data onto a file on the host PC. 

I see that out.lid file is created in the ramdisk every time I try to get the remote data but the file is not written onto a .csv file on the host. I decoded the reading of out.lid from RemoteData.class file to get byte-by-byte data with ' ' as termination. I am not able to read that data as well properly. 
I get characters ranging from 0 to 255 (ASCII) while I expect numbers (ASCII - 48 to 57) and probably alphabets (ASCII - 65 to 90, 97 to 122).

**Comment by GavinMorleyLab** [comment]
Hi Raghav,

Sorry but I don't know how to help with either of the problems you mention. The RePLIA software is not maintained anymore, and there are other implementations of Red-Pitaya lock-in amplifiers that are better eg:
https://marceluda.github.io/rp_lock-in_pid/

Cheers, Gavin

--
Prof Gavin W Morley
Director of Warwick Quantum
https://warwick.ac.uk/gavinmorley
https://warwick.ac.uk/WarwickQuantum

From: Raghav Sah ***@***.***>
Sent: Thursday, December 28, 2023 5:34 AM
To: WarwickEPR/RePLIA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [WarwickEPR/RePLIA] Unable to write data using LIAControl.jar (Issue #2)


I tried using LIAControl.jar to write the lock-in data onto a file on the host PC.

I see that out.lid file is created in the ramdisk every time I try to get the remote data but the file is not written onto a .csv file on the host. I decoded the reading of out.lid from RemoteData.class file to get byte-by-byte data with ' ' as termination. I am not able to read that data as well properly.
I get characters ranging from 0 to 255 (ASCII) while I expect numbers (ASCII - 48 to 57) and probably alphabets (ASCII - 65 to 90, 97 to 122).

-

**Comment by sahraghav57** [comment]
Hi Gavin, 
Thanks for your response and suggestion. 
We had been using the software that you mentioned. When data is exported, this software has a resolution of 1mV (in LV (+-1V) input setting). 1mV resolution looks like a 10-bit ADC output. Is there any other way to get a 14-bit ADC output? We aim to distinguish the voltage in micro-volt range.  Could you perhaps suggest something that could help us with this?

Thanks, 
Raghav.

**Comment by GavinMorleyLab** [comment]
Sorry but I don't know how to help with that.
