### ISSUE TITLE
Exported data from lock-in is truncated in decimal places.

### ISSUE THREAD

**Issue by sahraghav57** [WarwickEPR/RePLIA#3]
I am trying the lock-in feature in RedPitaya. 
https://marceluda.github.io/rp_lock-in_pid/

On the GUI it shows me up to 4 decimal places in harmonic lock-in.
![ss](https://github.com/WarwickEPR/RePLIA/assets/38662329/05b1fe37-62ef-4dff-95d0-6cfd5602053f)

But when I try to save the lock-in data, it stores in voltage up to 3 decimal places. 
![ss2](https://github.com/WarwickEPR/RePLIA/assets/38662329/fa530429-4f2a-4158-b480-c7bd68ae15f7)

I believe that this is a solvable bug for experiments requiring precise control. Any insights to solve this issue is much appreciated. 

Many thanks, 
Raghav.

**Comment by GavinMorleyLab** [comment]
Sorry but I don't know how to help with that as my team were not involved in writing that code. We use Zurich Instruments lock ins for our research papers.
